ROOT_PATH = './'
VICUNA_PATH = f"{ROOT_PATH}/vicuna-7b-v1.5"
LLAMA_PATH = f"{ROOT_PATH}/Llama-2-7b-hf"
FALCON_PATH = f"{ROOT_PATH}/falcon-7b-instruct"

ATTACK_TEMP = 1
TARGET_TEMP = 0
ATTACK_TOP_P = 0.9
TARGET_TOP_P = 1
